// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyXfBX9i7Ha0LQC5TMT8eczBbnBecbtH0',
    appId: '1:304291515936:web:199d8760e577fbe06bb645',
    messagingSenderId: '304291515936',
    projectId: 'sociout-app-qasbd0e',
    authDomain: 'sociout-app-qasbd0e.firebaseapp.com',
    storageBucket: 'sociout-app-qasbd0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrzwSfIQq28Wif0Lswk0m-1zpEcQpahRM',
    appId: '1:304291515936:android:0e61eeeadf9926586bb645',
    messagingSenderId: '304291515936',
    projectId: 'sociout-app-qasbd0e',
    storageBucket: 'sociout-app-qasbd0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnNB-NhxycA5SVq2mgKMlq5B06rbS33mM',
    appId: '1:304291515936:ios:d85f48450dcef4836bb645',
    messagingSenderId: '304291515936',
    projectId: 'sociout-app-qasbd0e',
    storageBucket: 'sociout-app-qasbd0e.appspot.com',
    iosBundleId: 'com.sociout.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnNB-NhxycA5SVq2mgKMlq5B06rbS33mM',
    appId: '1:304291515936:ios:d85f48450dcef4836bb645',
    messagingSenderId: '304291515936',
    projectId: 'sociout-app-qasbd0e',
    storageBucket: 'sociout-app-qasbd0e.appspot.com',
    iosBundleId: 'com.sociout.app',
  );
}
